// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vector_intersection
StringVector vector_intersection(StringVector v1, StringVector v2);
RcppExport SEXP _mulset_vector_intersection(SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< StringVector >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(vector_intersection(v1, v2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mulset_vector_intersection", (DL_FUNC) &_mulset_vector_intersection, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mulset(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
