# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vector_intersection <- function(v1, v2) {
    .Call('_mulset_vector_intersection', PACKAGE = 'mulset', v1, v2)
}

